const colors = [
  'Burgundy',
  'Sedona',
  'Wanderlust',
  'Pink',
  'Blue',
  'Burnt Orange',
  'Lavendar',
  'Dark Blue ',
  'Forest Green ',
  'Navy Blue',
  'Light Gray ',
  'Light Pink',
  'Ginger',
  'Rose',
  'Sage',
  'Cream',
  'Steel',
  'Clay',
  'Clay Plus',
  'Black',
  'Cheetah',
  'Black ',
  'Aqua',
  'Steel Wave',
  'Wheat Cream',
  'Clay ',
  'Clay map ',
  'Flower Cream',
  'Berry',
  'Latte',
  'Granite',
  'Cream and Burnt Orange Triple Dot',
  'Sage w/ Modern Rainbow',
  'Pink Heart',
  'Latte Dot',
  'White',
  'Cobalt',
  'Mustard',
  'Burnt Orange Dot',
  'Cream Pattern',
  'Gray',
  'Gray Dot',
  'Seafoam',
  'Granite Gray',
  'Tan',
  'Dark Red',
  'Camo',
  'Brown '
]
export default colors
